import type { NextPage } from "next";
import Head from "next/head";
import Filters from "../src/components/filters/filters";
import IntroductionCard from "../src/components/IntroductionCard";
import Card from "../src/UI/card";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Github API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IntroductionCard />
      <div className="flex bg-stone-100 rounded-xl h-20 w-full pt-4 mt-8 mx-auto md:w-2/3 lg:w-1/2">
        <Card text={"Search by User"} navigation={"searchUsers"} />
        <Card text={"Search by Repo"} navigation={"searchRepos"} />
      </div>
    </div>
  );
};

export default Home;
